CC = gcc
CFLAGS = -g -w -Wall

main: ../ExpressionEvaluator/main.c
	$(CC) $(CFLAGS) -o ../ExpressionEvaluator/main ../ExpressionEvaluator/main.c
	echo "Compiled ✅"

clean:
	rm ../ExpressionEvaluator/main
	echo "Cleaned 🧹"
