CP = gcc
CFLAGS = -g -w -Wall

main: ../ImplementationB+tree/main.c
	$(CP) $(CFLAGS) -o ../ImplementationB+tree/main.out ../ImplementationB+tree/main.c
	echo "Compiled main.c ✅"

clean:
	rm *.out
	echo "Cleaned 🧹"