CP = gcc
CFLAGS = -g -w -Wall

BTree:
	$(CP) $(CFLAGS) -o ../ImplementationB+tree/B_tree.out ../ImplementationB+tree/B_tree.c
	echo "Compiled main.c ✅"
	./B_tree.out

MWayTree:
	$(CP) $(CFLAGS) -o ../ImplementationB+tree/MWayTree.out ../ImplementationB+tree/MWayTree.c
	echo "Compiled main.c ✅"
	./MWayTree.out

B+Tree:
	$(CP) $(CFLAGS) -o ../ImplementationB+tree/B+_tree.out ../ImplementationB+tree/B+_tree.c
	echo "Compiled main.c ✅"
	./B+_tree.out


clean:
	rm *.out
	echo "Cleaned 🧹"