CP = gcc
CFLAGS = -g -w -Wall

main:
	$(CP) $(CFLAGS) -o ../ImplementationB+tree/main.out ../ImplementationB+tree/main.c
	echo "Compiled main.c ✅"

run: 
	../ImplementationB+tree/main.out

clean:
	rm *.out
	echo "Cleaned 🧹"